### ISSUE TITLE
Second Evaluation Feedback

### ISSUE THREAD

**Issue by vikasTmz** [lagadic/visp_cao_editor#19]
Taken from the feedback:
> One situation where the Blender API does not allow us to do exactly what we wanted.

Can we elaborate on what the API fails to accomplish?

> The other one concerns the Qt part, to render a primitive using Qt3D. As both of us have basically no experience with Qt3D and as it is still an "experimental" module, I think what we (I included) could have done better is to evaluate the feasibility before. It is important to have guarantees before choosing a "framework" and have fallback solutions if needs be.

The guarantees I considered before choosing Qt to implement the model viewer/editor was of other open source projects that have done this. [Meshlab](https://github.com/cnr-isti-vclab/meshlab) is one that is built on Qt. But since this doesn't use Qt3D, I agree that some feasibility evaluation should have been done first.
Initially I thought this project could be built on a fork of an earlier version of projects like Meshlab, but maintaining it would be difficult considering the changes being made in Qt.

Qt also supports porting `three.js` codes using `QtCanvas3D`.

**Comment by s-trinh** [comment]
I was just nitpicking. I was trying to (badly) illustrate that in software development project not everything will go as we planned.

> One situation where the Blender API does not allow us to do exactly what we wanted.

I meant the possibility to get the ordered list of selected points. I picked (maybe badly) this example to show how finding workaround is important.

> > The other one concerns the Qt part, to render a primitive using Qt3D. As both of us have basically no experience with Qt3D and as it is still an "experimental" module, I think what we (I included) could have done better is to evaluate the feasibility before. It is important to have guarantees before choosing a "framework" and have fallback solutions if needs be.

> The guarantees I considered before choosing Qt to implement the model viewer/editor was of other open source projects that have done this. Meshlab is one that is built on Qt. But since this doesn't use Qt3D, I agree that some feasibility evaluation should have been done first.
> Initially I thought this project could be built on a fork of an earlier version of projects like Meshlab, but maintaining it would be difficult considering the changes being made in Qt.

Nothing wrong with Qt, we even stated to use Qt to create an application to edit a `.cao` model file in our GSoC wiki page.

> But since this doesn't use Qt3D, I agree that some feasibility evaluation should have been done first.

Yes, this was my point: with little retrospect, what could have been done better, even if everything is good so far.
