### ISSUE TITLE
Final Evaluation

### ISSUE THREAD

**Issue by vikasTmz** [lagadic/visp_cao_editor#24]
![screenshot from 2017-08-26 18 58 25](https://user-images.githubusercontent.com/11690674/29741779-98c69aa2-8a90-11e7-87c6-b968825da63d.png)

Suggestions on what should be filled.
[Link](https://developers.google.com/open-source/gsoc/help/work-product) to **Work Submission Instructions**.

**Comment by s-trinh** [comment]
My suggestion is to add a [wiki](https://github.com/lagadic/visp_cao_editor/wiki) (GSoC 2017) page to store the following information:

- a quick sentence to present yourself?
- describe the two parts of the project + the [link](https://github.com/lagadic/visp/wiki/GSoC_2017) to the ViSP GSoC project page
- for each project, describe the features you have implemented + the links to the corresponding pull requests
- link to your proposal?
- add some screenshots + the links to the corresponding tutorials
- external references? (Qt3D documentation, Blender API documentation, links to some examples or projects you used for inspiration if any, ...)
- conclusion?

If you want you can:

- add your feedback (difficulties, timeline, ...) about the GSoC project
- add future improvements?
- some random examples:
  - [GSoC/2016/StatusReports/StefanToncu](https://community.kde.org/GSoC/2016/StatusReports/StefanToncu)
  - [GOOGLE SUMMER OF CODE'16 WITH TIMVIDEOS.US](https://shashankgangrade.wordpress.com/gsoc-final/)
  - [Google Summer of Code 2016/Abstracting device address allocation](https://wiki-libvirt.rhcloud.com/page/Google_Summer_of_Code_2016/Abstracting_device_address_allocation)
  - [GSoC Wrapup!](http://www.aviraldg.com/p/gsoc-2016-wrapup/)
  - [Adding Python 3 compatibility and mypy annotations to Zulip](https://paper.dropbox.com/doc/Adding-Python-3-compatibility-and-mypy-annotations-to-Zulip-FehitXSQq761g39O31eE3)

**Comment by vikasTmz** [comment]
I've added a wiki page in my fork. [GSoC-Wiki](https://github.com/vikasTmz/visp_cao_editor/wiki/GSoC-2017-with-ViSP) _Few changes to be made_

Can I have the necessary permissions inorder to add one on this repository?

**Comment by s-trinh** [comment]
It should be good now.
