### ISSUE TITLE
Primitive: 3D Face

### ISSUE THREAD

**Issue by s-trinh** [lagadic/visp_cao_editor#7]
A 3D face can be modeled by 3 to N points. The order of the points can matter when computing the visibility from face normal.

Interaction description:

- in edit mode, the user selects a particular point, he can see the corresponding coordinate in the **transform** > **vertex** field (as usual)
![3d_coordinate](https://cloud.githubusercontent.com/assets/8035162/26731686/1dafe74c-47b5-11e7-8751-1b2f4fade5db.png)
- the user clicks on a button to add the current selected point in the list

![3d_face](https://cloud.githubusercontent.com/assets/8035162/26734367/0308e728-47be-11e7-87d1-e09ece526f21.png)

- a proposal is to use a [drop down list](https://blender.stackexchange.com/questions/42879/create-drop-down-list-in-menu-panel) to display the desired point in the list
- the user can also use the drop down list to select the point he wants to edit in the text boxes below
- if possible, the user selects multiple points and can then add all the selected points in the list

![3d_line_multiple_selection](https://cloud.githubusercontent.com/assets/8035162/26734101/2db50764-47bd-11e7-9a68-efd9c5763d13.png)

**Comment by vikasTmz** [comment]
Is this feature introduced here and in #6 an alternate to simplifying a model? Like instead of simplifying  just choose the important contour points?

**Comment by s-trinh** [comment]
Yes, after some reflexion, we prefer the approach where the user selects directly the contour points he wants for 3D lines and 3D faces:

- it is easier to use for a novice user
- no need to prefilter the CAD model
- more flexible: the user can model some primitives, test the tracking, model other primitives or remove some elements, test, etc.

**Comment by vikasTmz** [comment]
From #8 
> in complex CAD models we have, the object is not decomposed of multiple primitives in the object tree view and we don't want to force the user to prefilter and/or group each primitive in a specific group

Simplifying or decomposing models isn't difficult once important vertices are selected. 
Below are some simple steps that can be done to generate faces from the selected vertices.

**1. Select vertices**
![screenshot from 2017-06-03 12 55 17](https://cloud.githubusercontent.com/assets/11690674/26752960/6c29c1a4-4864-11e7-9600-bbe1d0690cee.png)

**2. `Y` to seperate vertices/ edges and `P` to create a new mesh for those separated vertices/ edges**
![screenshot from 2017-06-03 12 55 50](https://cloud.githubusercontent.com/assets/11690674/26753013/b311f25c-4865-11e7-9e6b-5ead4bd8361c.png)

**3. Now the user can select edges/vertices/faces and then `X` to delete them. `Limited Dissolve` can now be used to reduce number of vertices/ edges further and maintain the contour** [this step is optional]

**4. `F` to create a face from the new set of vertices**
![screenshot from 2017-06-03 13 49 56](https://cloud.githubusercontent.com/assets/11690674/26753011/a85e9b26-4865-11e7-8825-475d25409288.png)

**Comment by vikasTmz** [comment]
The advantage of having these primitives exist in the scene is it would be easy to manage them.
But if they are to be managed in a list as just data points, the list would be very large for even a simple model like `cubesat` and it would be hard for the user then to remove/ disable a random list of points/ lines from the tree view without any 3D representation.

But let me go ahead and implement these features and see how it turns out when working with complex models.

**Comment by vikasTmz** [comment]
> The advantage of having these primitives exist in the scene is it would be easy to manage them.
But if they are to be managed in a list as just data points, the list would be very large for even a simple model like cubesat and it would be hard for the user then to remove/ disable a random list of points/ lines from the tree view without any 3D representation.

Any reviews on this?

**Comment by s-trinh** [comment]
Sorry for the delay.

> But if they are to be managed in a list as just data points, the list would be very large for even a simple model like cubesat and it would be hard for the user then to remove/ disable a random list of points/ lines from the tree view without any 3D representation.

- the 3D face panel should allow to model only one face
- a [tree view box](https://wiki.blender.org/index.php/Dev:Ref/Proposals/UI/TreeView_Box) should be a good candidate to display the list of points the user has chosen to model a face, as it is rare to model a face by more than 10 points
- it should be possible to highlight the current selected point in the tree view ([link 1](https://blender.stackexchange.com/questions/23113/select-vertices-of-mesh-in-python), [link 2](https://blender.stackexchange.com/questions/43127/how-do-i-select-specific-vertices-in-blender-using-python-script)) in the main view

The current status of the pull request for me is:

- it is possible to model multiples geometric primitives (e.g. 2 circles, 3 faces, 4 lines) but each primitive (except for 3D face) have to be a specific object group?
- the last commits introduce the possibility to copy directly the coordinates of the selected point by a click on a button and display the good number of points for circle and cylinder

Is it correct (I don't have access to my dev machine right now) or I missed something?
If so, this pull request could be a first Blender plugin.

---

The second plugin I would like to have is:

- one tree view that lists the list of geometric primitives added by the user (for example at the bottom of the current panel)
- 3D circle and 3D cylinder are good but a click to "set propertie" (to be renamed to a more appropriate name like "add") will add the primitive to the primitive tree view
- 3D face panel will have one button to add the selected points in a list, the points will be displayed in another tree view
- 3D line panel will have only two points / 2 buttons to copy the coordinate from the current selected point
- a text box to let the user set a name to the primitive modelled

We should proceed iteratively:

- first version (model primitives, remove a primitive): 
  - a tree view to display the list of added primitives (only display the list of primitive and remove, with generic name like `face1`, `circle#1`, `circle#2`, etc.)
  - 3D circle and 3D cylinder with a button to add these primitives
  - 3D line similar to 3D circle and cylinder
  - 3D face: a button to add all the selected points in a list but no display/edit and add directly the primitive in the list of primitives
- second version (edit a primitive):
  - allow the user to edit a primive by selecting it in the primitive tree view and update the corresponding 3D face, line, circle or cylinder panels with the according properties
  - 3D face will display in a tree view the list of points that model the face, visual feedback (highlight the current point) and edition possible
- third version (optional):
  - possibility to set directly the LOD properties and primitive names
  - hierarchical model by changing the "level" of the primitive in the primitive tree view

Do you think it is feasible? In the (global) project, I would like to prioritize on this 2nd Blender plugin. If we are short in time, some optional features could be dropped (for example, import a `.cao` in Blender) or simplify.

**Comment by vikasTmz** [comment]
> The current status of the pull request for me

Yes, these have been implemented.

I believe I can finish the second plugin (including version 1,2,3) within the given deadlines in my timeline.
The import plugin can also be done since I've alloted a week for that during the month of August and also 2 weeks after that to work on any improvements.

**Comment by vikasTmz** [comment]
There could be one issue with this:

- To get the selected `vertices` of a mesh in blender, we have to traverse through all the `vertices` of the mesh and see if the `selected flag` is `true`. There is no function call that is triggered on selecting the vertex in the scene.

- So the problem here is that the user will have to make sure that he/she selects the `vertices` in the order their `indices` are stored in blender i.e if you look at the screenshot below, the `vertices` that the user selects to model a face using points have to be selected in their order of their `indices` such that this order is maintained on traversing through the entire mesh to find the selected `vertices`. 

![screenshot from 2017-06-11 20 07 33](https://user-images.githubusercontent.com/11690674/27012882-ce8195d8-4ee1-11e7-9379-96288904c6ce.png)

This is fine for simple models.

- But for a complex model like this:
![screenshot from 2017-06-11 20 18 21](https://user-images.githubusercontent.com/11690674/27012970-277009b2-4ee3-11e7-85f3-f27d4101c839.png)

 it could be difficult to ensure this order. If the user selects the vertices `11080->11081->11120->11091`, there is no way of knowing whether `11120` was selected before `11091`.

**Solution**:
If the user were to follow the steps I mentioned in the **4 steps** few comments above (_June 3_), this issue can be solved.

**Comment by s-trinh** [comment]
Ok. Let's move to the tutorial part for now.

**Comment by vikasTmz** [comment]
I believe I've found a solution to the above. The new PR has the implementation.
Basically after the user selects the vertices:

-  A new mesh is formed with these vertices.
- Faces/edges are added.
- If `polycount` > 1: `Limited Dissolve` is applied.

Therefore all user has to do is to select the vertices and add it as a primitive. Editing these vertices may be tricky, so right now only add/delete is possible.

**Comment by s-trinh** [comment]
Done in #16
